{
  "image": "node:4",
  "stages": [
    "test",
    "deploy"
  ],
  "test": {
    "stage": "test",
    "script": [
      "npm install",
      "npm test"
    ]
  },
  "pages": {
    "stage": "deploy",
    "script": [
      "cp -r docs pages/",
      "cp -r coverage pages/",
      "cp -r architecture pages/",
    ],
    "artifacts": {
      "paths": [
        "pages"
      ]
    },
    "only": [
      "master"
    ]
  }
}
